/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Student */
        post: operations["register_student_auth_register_student_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/helper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Helper */
        post: operations["register_helper_auth_register_helper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Email */
        get: operations["verify_email_auth_verify_email_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a refresh token for a new pair, invalidating the one presented.
         *
         *     Rotation matters: without it every refresh token ever issued stays usable
         *     for its full 30 days, so a single leaked token is a month of silent access
         *     that no logout can end. Here the presented token is denied-listed as part of
         *     the exchange, which also means replaying an old one is *detectable* — and a
         *     replay is either a stolen token or a broken client, never normal traffic.
         *
         *     Rotation is softened by a short grace window, because "never normal traffic"
         *     is not quite true for this app: the helper's UI and its GPS service isolate
         *     hold the same refresh token and reach 15-minute expiry together, so they
         *     legitimately refresh at the same instant. See `claim_rotation` for how both
         *     end up with the same pair instead of one of them being signed out mid-trip.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End this session: deny-list the access token and the refresh token.
         *
         *     Deleting tokens client-side was never logout — the tokens stayed valid on
         *     any device that had copied them. Revoking the refresh token is the part that
         *     matters, since it is the one worth 30 days.
         *
         *     A refresh token belonging to a *different* user is ignored rather than
         *     revoked, so this cannot be used to sign other people out.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/helpers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Helpers
         * @description List helper accounts — the admin panel's approval queue.
         *
         *     Note there is no auth code in this handler. The router guard already ran;
         *     by the time we are here the caller is a known, active admin.
         */
        get: operations["list_helpers_admin_helpers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/helpers/{helper_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Helper
         * @description Approve a pending helper so they can start sending GPS (spec §8).
         */
        post: operations["approve_helper_admin_helpers__helper_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend User
         * @description Suspend an account. Takes effect on the caller's very next request.
         *
         *     Immediate revocation is exactly what RULE 3 buys. A suspended user's access
         *     token is still cryptographically valid and unexpired — nothing can un-issue
         *     it. What stops them is `get_principal` reading a fresh snapshot that says
         *     `suspended` and raising 401. Skip the invalidation and that check reads a
         *     stale snapshot instead, so a suspended account keeps its access.
         */
        post: operations["suspend_user_admin_users__user_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description The emergency console's list — worst first, newest first within severity.
         *
         *     Backed by `ix_alerts_status_severity`, so the default view stays an index
         *     scan over open rows rather than a sort of the whole table as history grows.
         */
        get: operations["list_alerts_admin_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Alert
         * @description Claim an alert so two admins do not work the same incident.
         */
        post: operations["acknowledge_alert_admin_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/alerts/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Alert
         * @description Close an incident. A resolved alert keeps who acknowledged it and why.
         */
        post: operations["resolve_alert_admin_alerts__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/buses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bus
         * @description Create a new bus in the fleet.
         */
        post: operations["create_bus_admin_buses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/buses/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bus List
         * @description Create multiple buses at once (batch creation).
         */
        post: operations["create_bus_list_admin_buses_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/buses/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bus List
         * @description Create multiple buses at once (batch creation).
         */
        post: operations["create_bus_list_admin_buses_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/buses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Buses
         * @description The bus picker in the helper app.
         *
         *     Replaces typing a UUID by hand, which was the previous state of affairs and
         *     is exactly as error-prone as it sounds.
         */
        get: operations["list_buses_fleet_buses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routes */
        get: operations["list_routes_fleet_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Route
         * @description One route with its ordered stops — what the map draws.
         *
         *     `selectinload` fetches route_stops and their stops in two extra queries
         *     rather than one per stop. The lazy default would issue an N+1 storm on a
         *     route with thirty stops, on an endpoint every map load hits.
         */
        get: operations["get_route_fleet_routes__route_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stops */
        get: operations["list_stops_fleet_stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/trips/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Trip
         * @description Begin a trip. Everything the bus produces from now on binds to it.
         */
        post: operations["start_trip_helper_trips_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/trips/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Trip
         * @description Close the caller's live trip.
         *
         *     No trip id in the path: a helper has at most one live trip, enforced by a
         *     partial unique index, so there is nothing to disambiguate — and no id for a
         *     client to get wrong or forge.
         */
        post: operations["end_trip_helper_trips_end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/trips/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Trip
         * @description What the app calls on launch to recover state after a restart or crash.
         */
        get: operations["get_active_trip_helper_trips_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Seats
         * @description Report how full the bus is (spec §6 `seat_reports`).
         *
         *     Requires a live trip: an occupancy count with no trip cannot be attributed
         *     to a route or a time window, which is the only thing that makes it useful.
         */
        post: operations["report_seats_helper_seats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Raise Alert
         * @description Raise an alert from the emergency screen (spec §7.6).
         *
         *     Works without a live trip on purpose — a breakdown on the way to the depot
         *     is still a breakdown, and an SOS must never be refused on a technicality.
         *
         *     Severity is assigned by the server from the type; the client does not get a
         *     say, or every alert would arrive critical.
         */
        post: operations["raise_alert_helper_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Gps
         * @description Receive a batch of GPS fixes from a helper device (spec §7.3).
         *
         *     Writes the newest fix to `bus:{id}:pos` (TTL 60 s) for "where is bus 7 right
         *     now", publishes to the fleet channel for the admin live map, and XADDs every
         *     fix to the `gps_ingest` stream. The worker drains that stream into
         *     Elasticsearch.
         *
         *     Trip binding
         *     ------------
         *     If the helper has a live trip, its id rides along on every fix and the
         *     trip's bus wins over whatever the client sent — the server decides which bus
         *     a helper is driving, not the phone.
         *
         *     Fixes with no live trip are still accepted, with an empty `trip_id`. That is
         *     a **transition allowance** for the current helper build, which has no trip
         *     UI yet; it is why `trip_id` is nullable downstream. Once the app ships trip
         *     lifecycle, make this a 409 and delete this paragraph.
         */
        post: operations["ingest_gps_helper_gps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/track/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearby Buses
         * @description Buses with a recent fix within `radius_km`, closest first.
         *
         *     `collapse` on bus_id returns one hit per bus; the `_geo_distance` sort makes
         *     that hit the closest point and exposes its distance.
         */
        get: operations["nearby_buses_track_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description What is for sale. Readable by any signed-in account so the helper app can
         *     show a student what they should have bought.
         */
        get: operations["list_products_shop_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_shop_orders_get"];
        put?: never;
        /**
         * Create Order
         * @description Start a purchase and return the gateway URL to send the student to.
         *
         *     Idempotent on `idempotency_key`: a retried or double-tapped request returns
         *     the original order rather than charging twice. The uniqueness is enforced by
         *     the database, because a check-then-insert loses the race that makes this
         *     necessary in the first place.
         */
        post: operations["create_order_shop_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/payments/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Payment Return Get
         * @description Some gateway configurations redirect with a GET and query parameters.
         */
        get: operations["payment_return_get"];
        put?: never;
        /**
         * Payment Return Post
         * @description The normal case: SSLCommerz returns the student with a form POST.
         */
        post: operations["payment_return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/payments/ipn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Ipn
         * @description SSLCommerz reporting the outcome server to server.
         *
         *     This exists because the browser return cannot be relied on: a student who
         *     closes the tab, loses signal, or is redirected through a flaky network
         *     never reaches it, and their money is gone with no ticket to show for it.
         *     The IPN arrives regardless, which makes it the authoritative path and the
         *     return merely the fast one.
         *
         *     Answers 200 for outcomes SSLCommerz should stop retrying — including
         *     failures, which are settled facts. A 5xx is reserved for "ask again later",
         *     because that is what a retry can actually fix.
         */
        post: operations["payment_ipn_shop_payments_ipn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickets
         * @description The student's wallet. Scoped to the caller — never takes an id from the
         *     request, so one student cannot read another's tickets.
         */
        get: operations["list_tickets_shop_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/tickets/{ticket_id}/qr-material": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qr Material
         * @description Hand a student's device what it needs to generate boarding codes offline.
         *
         *     Scoped to the caller's own ticket — the id in the path is checked against
         *     the caller's student row, never trusted on its own. Without that, any
         *     student could ask for any ticket's private key by guessing a uuid, which
         *     would hand them the whole system.
         */
        get: operations["qr_material_shop_tickets__ticket_id__qr_material_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/tickets/{ticket_id}/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qr Image
         * @description Render the current boarding code as a PNG.
         *
         *     The offline path signs on the student's own device (see `qr-material`);
         *     this is the online convenience, and the only way to put a real rotating
         *     code in front of a scanner before the student app exists.
         *
         *     Signed here rather than handed over as data because the browser showing it
         *     has connectivity by definition — if it did not, it could not have asked.
         *
         *     Cached nowhere. The code is only valid for its 30-second slice, so a cached
         *     image is a rejected passenger; `no-store` also keeps it out of any proxy
         *     between here and the phone.
         */
        get: operations["qr_image_shop_tickets__ticket_id__qr_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticket Manifest
         * @description The offline ticket manifest (spec §7.5).
         *
         *     Synced at trip start on whatever signal is available. It carries public
         *     keys only, plus enough identity for the dead-phone fallback: a student
         *     whose battery died gives their student ID and the helper finds them here.
         *
         *     Only active tickets are listed, which is also how revocation reaches an
         *     offline helper — a revoked ticket simply stops appearing, and the staleness
         *     window is the time since their last sync.
         */
        get: operations["ticket_manifest_helper_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/redemptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Redemptions
         * @description Record boardings a helper's device accepted, online or hours ago.
         *
         *     Every item is answered individually. One forged code in a batch of forty
         *     must not cost the other thirty-nine — a helper who loses a route's worth of
         *     genuine boardings because a single scan was bad has lost real revenue.
         *
         *     Each result is committed on its own for the same reason: a later item
         *     failing must not roll back earlier valid ones.
         */
        post: operations["sync_redemptions_helper_redemptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveTripOut
         * @description The helper app's answer to "am I already tracking?" after a restart.
         */
        ActiveTripOut: {
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Bus Id
             * Format: uuid
             */
            bus_id: string;
            /**
             * Route Id
             * Format: uuid
             */
            route_id: string;
        };
        /** AlertOut */
        AlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source: components["schemas"]["AlertSource"];
            type: components["schemas"]["AlertType"];
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            /** Message */
            message: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Trip Id */
            trip_id: string | null;
            /** Bus Id */
            bus_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AlertRaiseIn */
        AlertRaiseIn: {
            type: components["schemas"]["AlertType"];
            /** Message */
            message?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
        };
        /** AlertResolveIn */
        AlertResolveIn: {
            /** Note */
            note?: string | null;
        };
        /**
         * AlertSeverity
         * @enum {string}
         */
        AlertSeverity: "critical" | "warning" | "info";
        /**
         * AlertSource
         * @enum {string}
         */
        AlertSource: "helper" | "student" | "system";
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "open" | "acknowledged" | "resolved" | "dismissed";
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "sos" | "breakdown" | "traffic_delay" | "accident" | "harassment" | "overcrowding" | "off_route" | "over_speed" | "gps_blackout" | "other";
        /** BusCreate */
        BusCreate: {
            /** Reg No */
            reg_no: string;
            /** Nickname */
            nickname?: string | null;
            /**
             * Capacity
             * @default 40
             */
            capacity: number;
            /** @default active */
            status: components["schemas"]["BusStatus"];
        };
        /** BusListCreate */
        BusListCreate: {
            /** Buses */
            buses: components["schemas"]["BusCreate"][];
        };
        /** BusOut */
        BusOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reg No */
            reg_no: string;
            /** Nickname */
            nickname: string | null;
            /** Capacity */
            capacity: number;
            status: components["schemas"]["BusStatus"];
        };
        /**
         * BusStatus
         * @enum {string}
         */
        BusStatus: "active" | "inactive" | "maintenance";
        /**
         * CheckoutOut
         * @description Where to send the student to pay.
         */
        CheckoutOut: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /** Tran Id */
            tran_id: string;
            /** Amount Paisa */
            amount_paisa: number;
            /** Currency */
            currency: string;
            status: components["schemas"]["OrderStatus"];
            /** Checkout Url */
            checkout_url: string;
        };
        /** GpsAccepted */
        GpsAccepted: {
            /** Accepted */
            accepted: number;
            /**
             * Bus Id
             * Format: uuid
             */
            bus_id: string;
            /** Trip Id */
            trip_id?: string | null;
        };
        /**
         * GpsBatch
         * @description A batch of buffered fixes from the helper device (spec §7.3: ~1-10 per ~5s).
         */
        GpsBatch: {
            /**
             * Bus Id
             * Format: uuid
             */
            bus_id: string;
            /** Points */
            points: components["schemas"]["GpsPointIn"][];
        };
        /** GpsPointIn */
        GpsPointIn: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Speed */
            speed?: number | null;
            /** Heading */
            heading?: number | null;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HelperOut
         * @description A helper account as the admin panel sees it.
         */
        HelperOut: {
            /**
             * Helper Id
             * Format: uuid
             */
            helper_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string | null;
            helper_status: components["schemas"]["HelperStatus"];
            user_status: components["schemas"]["UserStatus"];
            /** Approved By */
            approved_by: string | null;
        };
        /** HelperRegister */
        HelperRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
        };
        /**
         * HelperStatus
         * @enum {string}
         */
        HelperStatus: "pending" | "approved" | "suspended";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LogoutRequest
         * @description The refresh token to kill. The access token comes from the Bearer header.
         *
         *     Optional because a client that has already lost its refresh token should
         *     still be able to end the session it can prove it holds.
         */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * ManifestTicketOut
         * @description One row of the helper's offline ticket manifest (spec §7.5).
         *
         *     Carries the **public** key only. A lost or stolen helper phone therefore
         *     leaks nothing that can forge a boarding code — it can verify codes, not
         *     create them.
         *
         *     `rides_remaining` is a snapshot for display and for the dead-phone manual
         *     fallback. The server value is authoritative; this one is as fresh as the
         *     helper's last sync.
         */
        ManifestTicketOut: {
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /** Qr Public Key */
            qr_public_key: string;
            /** Student Name */
            student_name: string;
            /** Student Id No */
            student_id_no: string;
            /** Rides Remaining */
            rides_remaining: number | null;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            status: components["schemas"]["TicketStatus"];
        };
        /** OrderCreate */
        OrderCreate: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Amount Paisa */
            amount_paisa: number;
            /** Currency */
            currency: string;
            status: components["schemas"]["OrderStatus"];
            /** Tran Id */
            tran_id: string;
            /** Paid At */
            paid_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrderStatus
         * @description `initiated` means we created it; `pending` means the gateway has it.
         * @enum {string}
         */
        OrderStatus: "initiated" | "pending" | "paid" | "failed" | "cancelled" | "refunded";
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["ProductType"];
            /** Name */
            name: string;
            /** Price Paisa */
            price_paisa: number;
            /** Ride Count */
            ride_count: number | null;
            /** Validity Days */
            validity_days: number;
            /** Route Scope */
            route_scope: string | null;
        };
        /**
         * ProductType
         * @enum {string}
         */
        ProductType: "single" | "bulk" | "package";
        /**
         * QrMaterialOut
         * @description Everything a student's device needs to render boarding codes offline.
         *
         *     The private key leaves the server exactly once per sync, over an
         *     authenticated request, to the account that owns the ticket. That is the
         *     accepted trade in spec §7.5: a code that works with no signal has to be
         *     generated on the device, and generating it requires the key.
         *
         *     `server_time` is the clock-offset anchor. A phone whose clock is wrong
         *     would otherwise sign codes in the wrong time slice and be rejected at the
         *     door with nothing to explain why.
         */
        QrMaterialOut: {
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /** Qr Private Key */
            qr_private_key: string;
            /** Slice Seconds */
            slice_seconds: number;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Passenger Count */
            passenger_count: number;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
        };
        /** RedemptionBatchIn */
        RedemptionBatchIn: {
            /** Redemptions */
            redemptions: components["schemas"]["RedemptionIn"][];
        };
        /** RedemptionBatchOut */
        RedemptionBatchOut: {
            /** Results */
            results: components["schemas"]["RedemptionResultOut"][];
        };
        /**
         * RedemptionFlag
         * @description How much a recorded boarding should be trusted.
         *
         *     `ok` is the ordinary case. `duplicate_suspect` is what offline validation
         *     inevitably produces: two helper devices, neither able to see the other's
         *     nonce log, both accept the same QR. Cryptography cannot prevent that — only
         *     detection after the fact can, which is why the flag exists rather than a
         *     hard rejection that would break offline boarding entirely.
         * @enum {string}
         */
        RedemptionFlag: "ok" | "duplicate_suspect" | "invalid";
        /**
         * RedemptionIn
         * @description One boarding a helper's device recorded, online or hours earlier.
         */
        RedemptionIn: {
            /** Code */
            code: string;
            /** Device Id */
            device_id: string;
            /**
             * Redeemed At
             * Format: date-time
             */
            redeemed_at: string;
            /** Trip Id */
            trip_id?: string | null;
        };
        /**
         * RedemptionResultOut
         * @description What happened to one submitted boarding.
         *
         *     `accepted` tells the device whether to drop the row from its queue.
         *     A rejected code is dropped too — retrying a forged or expired code forever
         *     would be a queue that never drains.
         */
        RedemptionResultOut: {
            /** Nonce */
            nonce: string | null;
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Ticket Id */
            ticket_id?: string | null;
            /** Rides Remaining */
            rides_remaining?: number | null;
            flag?: components["schemas"]["RedemptionFlag"] | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RouteDetailOut
         * @description A route plus its ordered stops and drawn shape.
         *
         *     `polyline` is a Google-encoded polyline — a few thousand road points
         *     compressed to a string, so the map can draw the actual road rather than
         *     straight lines between stops without shipping a large coordinate array.
         */
        RouteDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            direction: components["schemas"]["RouteDirection"];
            /** Is Active */
            is_active: boolean;
            /** Polyline */
            polyline: string | null;
            /** Stops */
            stops: components["schemas"]["RouteStopOut"][];
        };
        /**
         * RouteDirection
         * @enum {string}
         */
        RouteDirection: "inbound" | "outbound";
        /** RouteOut */
        RouteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            direction: components["schemas"]["RouteDirection"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * RouteStopOut
         * @description A stop in the context of one route — sequence and timing included.
         */
        RouteStopOut: {
            /** Seq */
            seq: number;
            /** Scheduled Offset Min */
            scheduled_offset_min: number | null;
            stop: components["schemas"]["StopOut"];
        };
        /**
         * SeatReportIn
         * @description What the helper's counter screen sends.
         *
         *     `occupied` is bounded generously rather than at the bus capacity: a bus does
         *     run over capacity in Dhaka, and rejecting the report would lose the very
         *     data point that proves overcrowding.
         */
        SeatReportIn: {
            /** Occupied */
            occupied: number;
            /** Reported At */
            reported_at?: string | null;
        };
        /**
         * SeatStateOut
         * @description The dashboard's headline numbers.
         */
        SeatStateOut: {
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Occupied */
            occupied: number;
            /** Capacity */
            capacity: number;
            /** Free */
            free: number;
            /**
             * Reported At
             * Format: date-time
             */
            reported_at: string;
        };
        /** StopOut */
        StopOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** StudentRegister */
        StudentRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Student Id No */
            student_id_no: string;
            /** Department */
            department?: string | null;
            /** Batch */
            batch?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** TicketOut */
        TicketOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Rides Total */
            rides_total: number | null;
            /** Rides Remaining */
            rides_remaining: number | null;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            status: components["schemas"]["TicketStatus"];
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "active" | "exhausted" | "expired" | "revoked";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TripOut */
        TripOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Route Id
             * Format: uuid
             */
            route_id: string;
            /**
             * Bus Id
             * Format: uuid
             */
            bus_id: string;
            /**
             * Helper Id
             * Format: uuid
             */
            helper_id: string;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            status: components["schemas"]["TripStatus"];
            /** Actual Start */
            actual_start: string | null;
            /** Actual End */
            actual_end: string | null;
        };
        /**
         * TripStartRequest
         * @description What the helper picks in the app before pressing Start.
         */
        TripStartRequest: {
            /**
             * Bus Id
             * Format: uuid
             */
            bus_id: string;
            /**
             * Route Id
             * Format: uuid
             */
            route_id: string;
        };
        /**
         * TripStatus
         * @enum {string}
         */
        TripStatus: "scheduled" | "live" | "completed" | "cancelled";
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "student" | "helper" | "admin";
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "pending_email" | "active" | "pending_approval" | "suspended";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_student_auth_register_student_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_helper_auth_register_helper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HelperRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_helpers_admin_helpers_get: {
        parameters: {
            query?: {
                /** @description Filter by approval state; omit for all. */
                helper_status?: components["schemas"]["HelperStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelperOut"][];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_helper_admin_helpers__helper_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                helper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelperOut"];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_user_admin_users__user_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_admin_alerts_get: {
        parameters: {
            query?: {
                /** @description Defaults to open; pass null for all. */
                alert_status?: components["schemas"]["AlertStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_admin_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_admin_alerts__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bus_admin_buses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusOut"];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bus_list_admin_buses_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusListCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusOut"][];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bus_list_admin_buses_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusListCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusOut"][];
                };
            };
            /** @description Missing, malformed or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, but not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_buses_fleet_buses_get: {
        parameters: {
            query?: {
                /** @description Hide inactive/maintenance buses. */
                only_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routes_fleet_routes_get: {
        parameters: {
            query?: {
                only_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_fleet_routes__route_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_fleet_stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"][];
                };
            };
        };
    };
    start_trip_helper_trips_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_trip_helper_trips_end_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
        };
    };
    get_active_trip_helper_trips_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveTripOut"] | null;
                };
            };
        };
    };
    report_seats_helper_seats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_alert_helper_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRaiseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_gps_helper_gps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GpsBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpsAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nearby_buses_track_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_shop_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
        };
    };
    list_orders_shop_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
        };
    };
    create_order_shop_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_return_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    payment_return_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    payment_ipn_shop_payments_ipn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_tickets_shop_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
        };
    };
    qr_material_shop_tickets__ticket_id__qr_material_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QrMaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qr_image_shop_tickets__ticket_id__qr_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_manifest_helper_manifest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestTicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_redemptions_helper_redemptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedemptionBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedemptionBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
